### ISSUE TITLE
Encryption support

### ISSUE THREAD

**Issue by apoorvmote** [subscriptions-project/scenic-demo#213]
I have invested lot of time into amp and published subscription website.

But its so disappointing because I can just inspect on chrome on any paywall page find section with class called `paywall-section`. Just delete the class and access full content without paying for it. 

Your encryption project is out of date with Tinkey 1.5.0

I have made [issue](https://github.com/subscriptions-project/encryption/issues/14) there also.

Really looking forward to encrypt my content that cannot be accessed by deleting a class.

**Comment by elijahsoria** [comment]
Thanks Apoorv! I responded to the [issue](https://github.com/subscriptions-project/encryption/issues/14) in the encryption package. Let's keep discussion there.

Closing this issue for now.
